// jobs/2026-05-30__19-23-10/convex_nextjs_crud__CyBJfsb/artifacts/user/task-manager/src/app/page.tsx
"use client";

import { useState } from "react";
import { useQuery, useMutation } from "convex/react";
import { api } from "../../convex/_generated/api";

export default function Home() {
  const runId = process.env.NEXT_PUBLIC_ZEALT_RUN_ID || "default-run-id";
  const tasks = useQuery(api.tasks.getTasks, { runId });
  const addTask = useMutation(api.tasks.addTask);
  const toggleTask = useMutation(api.tasks.toggleTask);
  const deleteTask = useMutation(api.tasks.deleteTask);

  const [newTaskText, setNewTaskText] = useState("");

  const handleAddTask = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTaskText.trim()) return;
    await addTask({ text: newTaskText, runId });
    setNewTaskText("");
  };

  return (
    <main className="p-8 max-w-md mx-auto">
      <h1 className="text-2xl font-bold mb-4">Task Manager</h1>
      
      <form onSubmit={handleAddTask} className="mb-6 flex gap-2">
        <input
          type="text"
          value={newTaskText}
          onChange={(e) => setNewTaskText(e.target.value)}
          placeholder="Add a new task..."
          className="border p-2 flex-grow rounded text-black"
          data-testid="task-input"
        />
        <button
          type="submit"
          className="bg-blue-500 text-white px-4 py-2 rounded"
          data-testid="add-button"
        >
          Add
        </button>
      </form>

      {tasks === undefined ? (
        <p>Loading...</p>
      ) : (
        <ul className="space-y-2">
          {tasks.map((task) => (
            <li
              key={task._id}
              className="flex items-center justify-between p-3 border rounded bg-white text-black"
              data-testid="task-item"
            >
              <div className="flex items-center gap-3">
                <input
                  type="checkbox"
                  checked={task.isCompleted}
                  onChange={() =>
                    toggleTask({ id: task._id, isCompleted: !task.isCompleted })
                  }
                  data-testid="toggle-button"
                  className="w-5 h-5"
                />
                <span
                  className={task.isCompleted ? "line-through text-gray-400" : ""}
                >
                  {task.text}
                </span>
              </div>
              <button
                onClick={() => deleteTask({ id: task._id })}
                data-testid="delete-button"
                className="text-red-500 hover:text-red-700 font-bold px-2"
              >
                X
              </button>
            </li>
          ))}
        </ul>
      )}
    </main>
  );
}

// jobs/2026-05-31__18-51-05/convex_vue_integration__4dCJJYZ/artifacts/user/vue-convex-crud/src/App.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useQuery, useMutation } from 'convex-vue';
import { api } from '../convex/_generated/api';

const newTaskText = ref('');
const tasks = useQuery(api.tasks.get, {});
const { mutate: createTask } = useMutation(api.tasks.create);
const { mutate: toggleTask } = useMutation(api.tasks.toggle);
const { mutate: deleteTask } = useMutation(api.tasks.remove);

const addTask = async () => {
  if (newTaskText.value.trim()) {
    await createTask({ text: newTaskText.value });
    newTaskText.value = '';
  }
};

const handleToggle = async (id: any) => {
  await toggleTask({ id });
};

const handleDelete = async (id: any) => {
  await deleteTask({ id });
};
</script>

<template>
  <div class="container">
    <h1>Task List</h1>
    <div class="input-group">
      <input 
        id="new-task-input" 
        v-model="newTaskText" 
        type="text" 
        placeholder="Add a new task"
        @keyup.enter="addTask"
      />
      <button id="add-task-btn" @click="addTask">Add Task</button>
    </div>

    <ul v-if="tasks">
      <li v-for="task in tasks" :key="task._id" class="task-item">
        <span :style="{ textDecoration: task.isCompleted ? 'line-through' : 'none' }">
          {{ task.text }}
        </span>
        <button class="toggle-btn" @click="handleToggle(task._id)">
          {{ task.isCompleted ? 'Undo' : 'Complete' }}
        </button>
        <button class="delete-btn" @click="handleDelete(task._id)">Delete</button>
      </li>
    </ul>
    <p v-else>Loading tasks...</p>
  </div>
</template>

<style scoped>
.container {
  max-width: 600px;
  margin: 0 auto;
  padding: 2rem;
  text-align: center;
}

.input-group {
  margin-bottom: 2rem;
}

#new-task-input {
  padding: 0.5rem;
  font-size: 1rem;
  margin-right: 0.5rem;
}

#add-task-btn {
  padding: 0.5rem 1rem;
  font-size: 1rem;
  cursor: pointer;
}

.task-item {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0.5rem;
  border-bottom: 1px solid #ccc;
}

.toggle-btn, .delete-btn {
  margin-left: 0.5rem;
  padding: 0.25rem 0.5rem;
  cursor: pointer;
}
</style>
