// jobs/2026-05-31__20-39-44/convex_vue_integration__GrThqad/artifacts/user/vue-convex-crud/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useConvexQuery, useConvexMutation } from 'convex-vue'
import { api } from '../convex/_generated/api'

const newTaskText = ref('')

const { data: tasks } = useConvexQuery(api.tasks.get)

const { mutate: createTask } = useConvexMutation(api.tasks.create)
const { mutate: toggleTask } = useConvexMutation(api.tasks.toggle)
const { mutate: deleteTaskMut } = useConvexMutation(api.tasks.deleteTask)

function addTask() {
  const text = newTaskText.value.trim()
  if (!text) return
  createTask({ text })
  newTaskText.value = ''
}

function toggleTaskCompletion(id: string) {
  toggleTask({ id })
}

function deleteTask(id: string) {
  deleteTaskMut({ id })
}
</script>

<template>
  <div id="app">
    <h1>Task Manager</h1>
    <div class="add-task">
      <input
        id="new-task-input"
        v-model="newTaskText"
        type="text"
        placeholder="Add a new task..."
        @keyup.enter="addTask"
      />
      <button id="add-task-btn" @click="addTask">Add</button>
    </div>
    <ul class="task-list">
      <li v-for="task in tasks" :key="task._id" class="task-item">
        <span :class="{ completed: task.isCompleted }">{{ task.text }}</span>
        <button class="toggle-btn" @click="toggleTaskCompletion(task._id)">
          {{ task.isCompleted ? 'Undo' : 'Complete' }}
        </button>
        <button class="delete-btn" @click="deleteTask(task._id)">Delete</button>
      </li>
    </ul>
    <p v-if="!tasks || tasks.length === 0" class="empty-message">No tasks yet. Add one above!</p>
  </div>
</template>

<style scoped>
#app {
  max-width: 600px;
  margin: 0 auto;
  padding: 2rem;
  font-family: Arial, sans-serif;
}

h1 {
  text-align: center;
  color: #333;
}

.add-task {
  display: flex;
  gap: 0.5rem;
  margin-bottom: 1.5rem;
}

.add-task input {
  flex: 1;
  padding: 0.5rem;
  font-size: 1rem;
  border: 1px solid #ccc;
  border-radius: 4px;
}

.add-task button {
  padding: 0.5rem 1rem;
  font-size: 1rem;
  background-color: #4caf50;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

.add-task button:hover {
  background-color: #45a049;
}

.task-list {
  list-style: none;
  padding: 0;
}

.task-item {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.75rem;
  margin-bottom: 0.5rem;
  background-color: #f9f9f9;
  border-radius: 4px;
  border: 1px solid #eee;
}

.task-item span {
  flex: 1;
}

.task-item span.completed {
  text-decoration: line-through;
  color: #888;
}

.toggle-btn {
  padding: 0.25rem 0.5rem;
  font-size: 0.85rem;
  background-color: #2196f3;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

.toggle-btn:hover {
  background-color: #1976d2;
}

.delete-btn {
  padding: 0.25rem 0.5rem;
  font-size: 0.85rem;
  background-color: #f44336;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

.delete-btn:hover {
  background-color: #d32f2f;
}

.empty-message {
  text-align: center;
  color: #888;
}
</style>

// jobs/2026-05-30__19-23-10/convex_nextjs_crud__CyBJfsb/artifacts/user/task-manager/src/app/page.tsx
"use client";

import { useState } from "react";
import { useQuery, useMutation } from "convex/react";
import { api } from "../../convex/_generated/api";

export default function Home() {
  const runId = process.env.NEXT_PUBLIC_ZEALT_RUN_ID || "default-run-id";
  const tasks = useQuery(api.tasks.getTasks, { runId });
  const addTask = useMutation(api.tasks.addTask);
  const toggleTask = useMutation(api.tasks.toggleTask);
  const deleteTask = useMutation(api.tasks.deleteTask);

  const [newTaskText, setNewTaskText] = useState("");

  const handleAddTask = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTaskText.trim()) return;
    await addTask({ text: newTaskText, runId });
    setNewTaskText("");
  };

  return (
    <main className="p-8 max-w-md mx-auto">
      <h1 className="text-2xl font-bold mb-4">Task Manager</h1>
      
      <form onSubmit={handleAddTask} className="mb-6 flex gap-2">
        <input
          type="text"
          value={newTaskText}
          onChange={(e) => setNewTaskText(e.target.value)}
          placeholder="Add a new task..."
          className="border p-2 flex-grow rounded text-black"
          data-testid="task-input"
        />
        <button
          type="submit"
          className="bg-blue-500 text-white px-4 py-2 rounded"
          data-testid="add-button"
        >
          Add
        </button>
      </form>

      {tasks === undefined ? (
        <p>Loading...</p>
      ) : (
        <ul className="space-y-2">
          {tasks.map((task) => (
            <li
              key={task._id}
              className="flex items-center justify-between p-3 border rounded bg-white text-black"
              data-testid="task-item"
            >
              <div className="flex items-center gap-3">
                <input
                  type="checkbox"
                  checked={task.isCompleted}
                  onChange={() =>
                    toggleTask({ id: task._id, isCompleted: !task.isCompleted })
                  }
                  data-testid="toggle-button"
                  className="w-5 h-5"
                />
                <span
                  className={task.isCompleted ? "line-through text-gray-400" : ""}
                >
                  {task.text}
                </span>
              </div>
              <button
                onClick={() => deleteTask({ id: task._id })}
                data-testid="delete-button"
                className="text-red-500 hover:text-red-700 font-bold px-2"
              >
                X
              </button>
            </li>
          ))}
        </ul>
      )}
    </main>
  );
}
