// jobs/2026-05-30__19-23-10/convex_react_native__Q8URoG8/artifacts/user/my-app/App.tsx
import { ConvexProvider, ConvexReactClient } from "convex/react";
import { StyleSheet, Text, View, TextInput, Button, FlatList } from "react-native";
import { useQuery, useMutation } from "convex/react";
import { api } from "./convex/_generated/api";
import { useState } from "react";

const convex = new ConvexReactClient(process.env.EXPO_PUBLIC_CONVEX_URL as string);
const runId = process.env.EXPO_PUBLIC_RUN_ID as string || "default_run_id";

function TaskApp() {
  const tasks = useQuery(api.tasks.get, { runId }) || [];
  const addTask = useMutation(api.tasks.add);
  const [newTaskText, setNewTaskText] = useState("");

  const handleAddTask = () => {
    if (newTaskText.trim()) {
      addTask({ text: newTaskText, runId });
      setNewTaskText("");
    }
  };

  return (
    <View style={styles.container}>
      <Text style={styles.title}>Tasks</Text>
      <FlatList
        data={tasks}
        keyExtractor={(item) => item._id}
        renderItem={({ item }) => (
          <Text style={styles.task} testID="task-item">
            {item.text}
          </Text>
        )}
      />
      <TextInput
        style={styles.input}
        value={newTaskText}
        onChangeText={setNewTaskText}
        placeholder="New task..."
        testID="task-input"
      />
      <Button title="Add Task" onPress={handleAddTask} testID="add-button" />
    </View>
  );
}

export default function App() {
  return (
    <ConvexProvider client={convex}>
      <TaskApp />
    </ConvexProvider>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    padding: 20,
    marginTop: 50,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 20,
  },
  task: {
    fontSize: 18,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
  },
  input: {
    height: 40,
    borderColor: "gray",
    borderWidth: 1,
    marginBottom: 10,
    paddingHorizontal: 10,
  },
});

// jobs/2026-05-31__21-47-07/convex_vue_integration__wxr6R5g/artifacts/user/vue-convex-crud/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useConvexQuery, useConvexMutation } from 'convex-vue'
import { api } from '../convex/_generated/api'

// @ts-ignore
const runId = process.env.ZEALT_RUN_ID || "default";
const tableName = `tasks_${runId.replace(/-/g, '_')}`;

const { data: tasks } = useConvexQuery(api.tasks.get, { tableName });
const { mutate: createTask } = useConvexMutation(api.tasks.create);
const { mutate: toggleTask } = useConvexMutation(api.tasks.toggle);
const { mutate: deleteTask } = useConvexMutation(api.tasks.delete);

const newTaskText = ref('');

const addTask = async () => {
  if (!newTaskText.value.trim()) return;
  await createTask({
    tableName,
    text: newTaskText.value.trim(),
    isCompleted: false
  });
  newTaskText.value = '';
};

const handleToggle = async (id: string) => {
  await toggleTask({ tableName, id });
};

const handleDelete = async (id: string) => {
  await deleteTask({ tableName, id });
};
</script>

<template>
  <div class="app">
    <h1>Convex CRUD</h1>
    
    <div>
      <input id="new-task-input" v-model="newTaskText" @keyup.enter="addTask" placeholder="New task" />
      <button id="add-task-btn" @click="addTask">Add Task</button>
    </div>

    <ul v-if="tasks">
      <li v-for="task in tasks" :key="task._id" class="task-item">
        <span :style="{ textDecoration: task.isCompleted ? 'line-through' : 'none' }">
          {{ task.text }}
        </span>
        <button class="toggle-btn" @click="handleToggle(task._id)">Toggle</button>
        <button class="delete-btn" @click="handleDelete(task._id)">Delete</button>
      </li>
    </ul>
  </div>
</template>

<style scoped>
.app {
  max-width: 600px;
  margin: 0 auto;
  padding: 2rem;
}
.task-item {
  display: flex;
  gap: 1rem;
  margin-bottom: 0.5rem;
  align-items: center;
}
</style>
